---
title: "All you need is a tree"
output: 
  beamer_presentation:
    latex_engine: xelatex
    includes:
      in_header: "notations.tex"
date: "2022-07-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Setting

Let $\partition \in \mathcal{P}_N$ be an ordered partition of $\{1,\hdots,N\}$, that is:
\begin{align}
    \partition = \left\{ \partition_1, \ldots, \partition_K \right\} & & \bigcup_k \partition_k = [N] & & \partition_k \bigcap \partition_l = \emptyset & & 
\end{align}

Let $\mathbf{X} = \{\mathbf{x}_1,\hdots,\mathbf{x}_N\}$ be a dataset\footnote{This can be extended to a case where $\mathbf{X}$ is an adjacency matrix.}. We suppose that all datapoints belonging to the same element of the partition are independent and identically distributed, \textit{i.e.} conditional independence:
$$p(\mathbf{x}|\mathbf{c})=\prod_k \int_\theta \prod_{i \in c_k}p(\mathbf{x}_i|\theta)p(\theta)d\theta$$


## Setting

$$\lobs(\mathbf{X},\partition_k)=\log\left(\int_\theta \prod_{i \in c_k}p(\mathbf{x}_i|\theta)p(\theta)d\theta\right)$$

In case of exponential Familly observations :

$$p(\bx|\theta)=\exp\left(\gamma(\theta).T(\bx)-A(\theta)+B(\bx)\right)$$ and $\lobs(\mathbf{X},\partition_k)=\phi(\sum_{i\in\partition_k}T(\bx_i))$

## Setting, MAP clustering

$$\hat{\partition}=\arg\max_{\partition}p(\mathbf{x},\partition)=\arg\max_{\partition}p(\mathbf{x}|\partition)p(\partition)$$
We need to define a prior for $\partition$ : $p(\partition)?$


## Chinese restaurant process

Process :
\begin{itemize}
    \item $\frac{\alpha}{n+\alpha}$ new table
    \item $\frac{n_k}{n+\alpha}$ at table $k$ 
\end{itemize}

Distribution
$$p(\mathbf{c}|\alpha)=\frac{\Gamma(\alpha)\alpha^{K}}{\Gamma(\alpha+N))}\prod_{k}\Gamma(n_k)$$


## Uniform

Completely uniform:
$p(\partition)=\frac{1}{\sum_{k=1}^N\mathcal{B}_n^k k!}$

Uniform in $k$ and then uniform over the partitions with $k$ elements:
\begin{eqnarray}
p(K)&=&\frac{1}{N}\\
p(\partition|K)&=&\frac{1}{\mathcal{B}_n^k k!}
\end{eqnarray}


## Uniform

Uniform in $k$, then uniform over possible counts and then uniform over the partitions with $k$ elements and the specific counts:
\begin{eqnarray}
p(K)&=&\frac{1}{N}\\
p(\mathbf{n}|K)&=&\binom{N-1}{K-1}^{-1}\\
p(\mathbf{c}|\mathbf{n})&=&\frac{1}{N!}\prod_kn_k! \times \mathbf{1}_{\{c / \mathbf{n}_\mathbf{c} = \mathbf{c} \}} \times \mathbf{1}_{\{c / \vert c \vert = K \}}
\end{eqnarray}

## Truncated geometric over K


\begin{eqnarray}
p(K)&=&\Ucolor{\frac{1}{1-\alpha^N}\alpha^{K-1}(1-\alpha)}\\
p(\mathbf{n}|K)&=&\frac{1}{C_{N-1}^{K-1}}\\
p(\mathbf{c}|\mathbf{n})&=&\frac{1}{N!}\prod_kn_k! \times \mathbf{1}_{\{c / \mathbf{n}_\mathbf{c} = \mathbf{c} \}} \times \mathbf{1}_{\{c / \vert c \vert = K \}}
\end{eqnarray}

$\alpha=1$ is equivalent to uniform, $\alpha=0$ to a dirac at $k=1$.

$$p(\mathbf{c}|\alpha)= p (\mathbf{c}, \mathbf{n}_\mathbf{c}, K_\mathbf{c}) = \frac{1}{1-\alpha^N}\alpha^{K-1}(1-\alpha)\frac{1}{C_{N-1}^{K-1}}\frac{1}{N!}\prod_kn_k!$$
