# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_ldirpost`, beta, n, lambda, lpi)
}

grad_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_grad_ldirpost`, beta, n, lambda, lpi)
}

dH_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_dH_ldirpost`, beta, n, lambda, lpi)
}

z_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_z_ldirpost`, beta, n, lambda, lpi)
}

logdetH_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_logdetH_ldirpost`, beta, n, lambda, lpi)
}

iH_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_iH_ldirpost`, beta, n, lambda, lpi)
}

H_ldirpost <- function(beta, n, lambda, lpi) {
    .Call(`_gtclust_H_ldirpost`, beta, n, lambda, lpi)
}

ldirpost_norm <- function(beta0, n, lambda, lpi) {
    .Call(`_gtclust_ldirpost_norm`, beta0, n, lambda, lpi)
}

dirichlet_evidence <- function(n, lambda, lpi, pi) {
    .Call(`_gtclust_dirichlet_evidence`, n, lambda, lpi, pi)
}

hclustcc_cpp <- function(nb, X, method_obj, display_progress) {
    .Call(`_gtclust_hclustcc_cpp`, nb, X, method_obj, display_progress)
}

bayesian_hclustcc_cpp <- function(nb, X, method_obj, display_progress, approx) {
    .Call(`_gtclust_bayesian_hclustcc_cpp`, nb, X, method_obj, display_progress, approx)
}

